app:
  description: ${app.name} is a Spring Boot application
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATA_BASE_URL:jdbc:postgresql://localhost:5432/demo}
    username: ${DATA_BASE_USER:${random.value}}
    password: ${DATA_BASE_PASSWORD:${random.value}}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        time_zone: ${TIME_ZONE:UTC}
      org:
        hibernate:
          envers:
            default_schema: public
            store_data_at_delete: true
server:
  error:
    include-stacktrace: never
management:
  endpoints:
    web:
      exposure:
        include: "*"
    loggers:
      enabled: true